### ISSUE TITLE
ValueError when using mode that includes "t"

### ISSUE THREAD

**Issue by jdidion** [rec/safer#6]
If the intention is for safer to be a drop-in replacement for the `open()` builtin, then it should support all the valid arguments for `mode`, including `t` (even though it's redundant).

```
>>> import safer
>>> safer.open("foo", "wt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jdidion/.pyenv/versions/xphyle/lib/python3.6/site-packages/safer.py", line 128, in open
    return _open(name, mode, buffering, make_parents, delete_failures, arg)
  File "/Users/jdidion/.pyenv/versions/xphyle/lib/python3.6/site-packages/safer.py", line 207, in _open
    fp = m(temp_file, mode, opener=opener)
ValueError: invalid mode: wt
```

**Comment by rec** [comment]
Oh, I even knew about `'t'` and I falsely believed that this would all flow through _without a test._

Moment pls.

**Comment by rec** [comment]
Done!

I'll release a new version in the next day or two.

**Comment by jdidion** [comment]
Thanks! With this fixed I should be able to use safer for file opening in https://github.com/jdidion/xphyle

**Comment by rec** [comment]
Well, then, I just pushed version 2.0.3 which has this change in it.  You should see it on Pypi by and by.

**Comment by jdidion** [comment]
Awesome, thanks!
